Increase test coverage
icarus-consulting/Yaapii.Xml pull request #3
Opened 2018-02-19 11:43 UTC by aveXcaesar

### Please check if the PR fulfills these requirements
- [x] I made sure that my code builds (VisualStudio & cake script: build.ps1)
- [x] I merged the master into this branch before pushing
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe: Tests

### What is the current behavior? (You can also link to an open issue here)
closes #2 

### What is the new behavior?
Moore tests

### Does this PR introduce a breaking change? (check one with "x")
- [ ] Yes
- [x] No

### If this PR contains a breaking change, please describe the impact and migration path for existing applications

###  Other information
closes #2

2020-11-27 09:59 UTC, aveXcaesar commented
@Meerownymous 
Merged with master

2021-01-14 09:28 UTC, Meerownymous requested changes

2021-01-14 09:28 UTC, Meerownymous commented on tests/Test.Yaapii.Xml/TidyFileList.cs
> +    public sealed class TidyFileList : IAction
missing header docs

2021-01-14 09:28 UTC, Meerownymous commented on tests/Test.Yaapii.Xml/TidyFileList.cs
> +        public TidyFileList(string root, IDictionary<string, string> files, Action action) : this(
missing header docs

2021-01-14 09:28 UTC, Meerownymous commented on tests/Test.Yaapii.Xml/XSLEnvelopeImplementation.cs
> +    public sealed class XSLEnvelopeImplementation : XSLEnvelope
missing header docs

2021-01-14 15:38 UTC, merged